trigger:
  branches:
    include:
    - '*'

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
    command: 'restore'
    feedsToUse: 'config'
    nugetConfigPath: './src/nuget.config'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  inputs: 
    SourceFolder: '$(Build.SourcesDirectory)/src/XI.B3BotManager.Monitor/bin/Release/netcoreapp3.1/'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/XI.B3BotManager.Monitor'

- task: PublishBuildArtifacts@1
  inputs:
    PathToPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'